image: Visual Studio 2017

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - set PATH=%PATH%;C:\Qt\5.12.1\msvc2017_64\bin
  - rustc --version
  - cargo --version
  - qmake --version
  - cl 
  # unit tests
  - set RUST_BACKTRACE=full
  - set TST_GIT_PATH=%APPVEYOR_BUILD_FOLDER%
  - set QML2_IMPORT_PATH=%APPVEYOR_BUILD_FOLDER%\build\lib\release

build_script:
  - mkdir build & cd build
  - qmake -config release ..
  - nmake

test_script:
  - test\release\test.exe

# package
after_test:
  - move app\bin gitbumr
  - del /s /q *.lib *.exp
  - xcopy "%QML2_IMPORT_PATH%\GitbumrComponents" gitbumr\GitbumrComponents /I
  - windeployqt --verbose 0 --qmldir %APPVEYOR_BUILD_FOLDER%\app gitbumr\gitbumr.exe
  - pushd gitbumr & 7z a ..\..\app.zip . & popd

artifacts:
  - path: app.zip
