image: Visual Studio 2017

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - set PATH=%PATH%;C:\Qt\5.11.3\msvc2017_64\bin
  - rustc --version
  - cargo --version
  - qmake --version
  - cl

build_script:
  - mkdir build & cd build
  - qmake -config release ..
  - nmake
  - pushd bin & dir & del *.exp,*.lib & popd # files for development only
  - windeployqt --verbose 0 --qmldir app bin\gitbumr.exe
  - move bin gitbumr
  - cd gitbumr & 7z a ..\app.zip .

test_script:
  - set TST_GIT_PATH=%APPVEYOR_BUILD_FOLDER%
  - set QML2_IMPORT_PATH=%APPVEYOR_BUILD_FOLDER%\build\lib\release
  - nmake check

artifacts:
  - path: app.zip

# rustup takes minutes to install
cache:
  - '%USERPROFILE%\.rustup -> appveyor.yml'


