image: Visual Studio 2017

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - set PATH=%PATH%;C:\Qt\5.12.1\msvc2017_64\bin
  - rustc --version
  - cargo --version
  - qmake --version
  - cl

build_script:
  - qmake -config release
  - nmake

test_script:
  - set TST_GIT_PATH=%APPVEYOR_BUILD_FOLDER%
  - set QML2_IMPORT_PATH=%APPVEYOR_BUILD_FOLDER%\lib\release
  - echo %QML2_IMPORT_PATH%
  - nmake check

after_test:
  - move app\bin gitbumr
  - windeployqt --verbose 0 --qmldir app gitbumr\gitbumr.exe
  - cd gitbumr & 7z a ..\app.zip .

artifacts:
  - path: app.zip

# rustup takes minutes to install
cache:
  - '%USERPROFILE%\.rustup -> appveyor.yml'
