image: Visual Studio 2017

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - set PATH=%PATH%;C:\Qt\5.11.2\msvc2017_64\bin
  - rustc --version
  - cargo --version
  - qmake --version
  - cl

build_script:
  - qmake -config release
  - nmake
  - pushd bin & del *.exp,*.lib & popd # files for development only
  - windeployqt --verbose 0 --qmldir app bin\gitbumr.exe

test: off

after_test:
  - move bin gitbumr
  - cd gitbumr & 7z a ..\app.zip .

artifacts:
  - path: app.zip

# rustup takes minutes to install
cache:
  - '%USERPROFILE%\.rustup -> appveyor.yml'


