/* generated by rust_qt_binding_generator */
use libc::{c_char, c_ushort, c_int};
use std::slice;
use std::char::decode_utf16;

use std::sync::Arc;
use std::sync::atomic::{AtomicPtr, Ordering};
use std::ptr::null;

use implementation::*;


#[repr(C)]
pub struct COption<T> {
    data: T,
    some: bool,
}

impl<T> COption<T> {
    #![allow(dead_code)]
    fn into(self) -> Option<T> {
        if self.some {
            Some(self.data)
        } else {
            None
        }
    }
}

impl<T> From<Option<T>> for COption<T>
where
    T: Default,
{
    fn from(t: Option<T>) -> COption<T> {
        if let Some(v) = t {
            COption {
                data: v,
                some: true,
            }
        } else {
            COption {
                data: T::default(),
                some: false,
            }
        }
    }
}


pub enum QString {}

fn set_string_from_utf16(s: &mut String, str: *const c_ushort, len: c_int) {
    let utf16 = unsafe { slice::from_raw_parts(str, to_usize(len)) };
    let characters = decode_utf16(utf16.iter().cloned())
        .map(|r| r.unwrap());
    s.clear();
    s.extend(characters);
}



#[repr(C)]
#[derive(PartialEq, Eq, Debug)]
pub enum SortOrder {
    Ascending = 0,
    Descending = 1,
}

#[repr(C)]
pub struct QModelIndex {
    row: c_int,
    internal_id: usize,
}


fn to_usize(n: c_int) -> usize {
    if n < 0 {
        panic!("Cannot cast {} to usize", n);
    }
    n as usize
}


fn to_c_int(n: usize) -> c_int {
    if n > c_int::max_value() as usize {
        panic!("Cannot cast {} to c_int", n);
    }
    n as c_int
}


pub struct AppQObject {}

pub struct AppEmitter {
    qobject: Arc<AtomicPtr<AppQObject>>,
}

unsafe impl Send for AppEmitter {}

impl AppEmitter {
    /// Clone the emitter
    ///
    /// The emitter can only be cloned when it is mutable. The emitter calls
    /// into C++ code which may call into Rust again. If emmitting is possible
    /// from immutable structures, that might lead to access to a mutable
    /// reference. That is undefined behaviour and forbidden.
    pub fn clone(&mut self) -> AppEmitter {
        AppEmitter {
            qobject: self.qobject.clone(),
        }
    }
    fn clear(&self) {
        let n: *const AppQObject = null();
        self.qobject.store(n as *mut AppQObject, Ordering::SeqCst);
    }
}

pub trait AppTrait {
    fn new(emit: AppEmitter,
        repositories: Repositories) -> Self;
    fn emit(&mut self) -> &mut AppEmitter;
    fn repositories(&self) -> &Repositories;
    fn repositories_mut(&mut self) -> &mut Repositories;
    fn add_repository(&mut self, path: String) -> u64;
    fn add_repository_get_last_error(&self) -> String;
    fn init(&mut self) -> ();
    fn repository_index(&self, id: u64) -> u64;
}

#[no_mangle]
pub extern "C" fn app_new(
    app: *mut AppQObject,
    repositories: *mut RepositoriesQObject,
    repositories_new_data_ready: fn(*mut RepositoriesQObject),
    repositories_layout_about_to_be_changed: fn(*mut RepositoriesQObject),
    repositories_layout_changed: fn(*mut RepositoriesQObject),
    repositories_data_changed: fn(*mut RepositoriesQObject, usize, usize),
    repositories_begin_reset_model: fn(*mut RepositoriesQObject),
    repositories_end_reset_model: fn(*mut RepositoriesQObject),
    repositories_begin_insert_rows: fn(*mut RepositoriesQObject, usize, usize),
    repositories_end_insert_rows: fn(*mut RepositoriesQObject),
    repositories_begin_move_rows: fn(*mut RepositoriesQObject, usize, usize, usize),
    repositories_end_move_rows: fn(*mut RepositoriesQObject),
    repositories_begin_remove_rows: fn(*mut RepositoriesQObject, usize, usize),
    repositories_end_remove_rows: fn(*mut RepositoriesQObject),
) -> *mut App {
    let repositories_emit = RepositoriesEmitter {
        qobject: Arc::new(AtomicPtr::new(repositories)),
        new_data_ready: repositories_new_data_ready,
    };
    let model = RepositoriesList {
        qobject: repositories,
        layout_about_to_be_changed: repositories_layout_about_to_be_changed,
        layout_changed: repositories_layout_changed,
        data_changed: repositories_data_changed,
        begin_reset_model: repositories_begin_reset_model,
        end_reset_model: repositories_end_reset_model,
        begin_insert_rows: repositories_begin_insert_rows,
        end_insert_rows: repositories_end_insert_rows,
        begin_move_rows: repositories_begin_move_rows,
        end_move_rows: repositories_end_move_rows,
        begin_remove_rows: repositories_begin_remove_rows,
        end_remove_rows: repositories_end_remove_rows,
    };
    let d_repositories = Repositories::new(repositories_emit, model);
    let app_emit = AppEmitter {
        qobject: Arc::new(AtomicPtr::new(app)),
    };
    let d_app = App::new(app_emit,
        d_repositories);
    Box::into_raw(Box::new(d_app))
}

#[no_mangle]
pub unsafe extern "C" fn app_free(ptr: *mut App) {
    Box::from_raw(ptr).emit().clear();
}

#[no_mangle]
pub unsafe extern "C" fn app_repositories_get(ptr: *mut App) -> *mut Repositories {
    (&mut *ptr).repositories_mut()
}

#[no_mangle]
pub unsafe extern "C" fn app_add_repository(ptr: *mut App, path_str: *const c_ushort, path_len: c_int) -> u64 {
    let mut path = String::new();
    set_string_from_utf16(&mut path, path_str, path_len);
    let o = &mut *ptr;
    let r = o.add_repository(path);
    r
}

#[no_mangle]
pub unsafe extern "C" fn app_add_repository_get_last_error(ptr: *const App, d: *mut QString, set: fn(*mut QString, str: *const c_char, len: c_int)) {
    let o = &*ptr;
    let r = o.add_repository_get_last_error();
    let s: *const c_char = r.as_ptr() as (*const c_char);
    set(d, s, r.len() as i32);
}

#[no_mangle]
pub unsafe extern "C" fn app_init(ptr: *mut App) -> () {
    let o = &mut *ptr;
    let r = o.init();
    r
}

#[no_mangle]
pub unsafe extern "C" fn app_repository_index(ptr: *const App, id: u64) -> u64 {
    let o = &*ptr;
    let r = o.repository_index(id);
    r
}

pub struct HistoryQObject {}

pub struct HistoryEmitter {
    qobject: Arc<AtomicPtr<HistoryQObject>>,
    new_data_ready: fn(*mut HistoryQObject),
}

unsafe impl Send for HistoryEmitter {}

impl HistoryEmitter {
    /// Clone the emitter
    ///
    /// The emitter can only be cloned when it is mutable. The emitter calls
    /// into C++ code which may call into Rust again. If emmitting is possible
    /// from immutable structures, that might lead to access to a mutable
    /// reference. That is undefined behaviour and forbidden.
    pub fn clone(&mut self) -> HistoryEmitter {
        HistoryEmitter {
            qobject: self.qobject.clone(),
            new_data_ready: self.new_data_ready,
        }
    }
    fn clear(&self) {
        let n: *const HistoryQObject = null();
        self.qobject.store(n as *mut HistoryQObject, Ordering::SeqCst);
    }
    pub fn new_data_ready(&mut self) {
        let ptr = self.qobject.load(Ordering::SeqCst);
        if !ptr.is_null() {
            (self.new_data_ready)(ptr);
        }
    }
}

#[derive(Clone)]
pub struct HistoryList {
    qobject: *mut HistoryQObject,
    layout_about_to_be_changed: fn(*mut HistoryQObject),
    layout_changed: fn(*mut HistoryQObject),
    data_changed: fn(*mut HistoryQObject, usize, usize),
    begin_reset_model: fn(*mut HistoryQObject),
    end_reset_model: fn(*mut HistoryQObject),
    begin_insert_rows: fn(*mut HistoryQObject, usize, usize),
    end_insert_rows: fn(*mut HistoryQObject),
    begin_move_rows: fn(*mut HistoryQObject, usize, usize, usize),
    end_move_rows: fn(*mut HistoryQObject),
    begin_remove_rows: fn(*mut HistoryQObject, usize, usize),
    end_remove_rows: fn(*mut HistoryQObject),
}

impl HistoryList {
    pub fn layout_about_to_be_changed(&mut self) {
        (self.layout_about_to_be_changed)(self.qobject);
    }
    pub fn layout_changed(&mut self) {
        (self.layout_changed)(self.qobject);
    }
    pub fn data_changed(&mut self, first: usize, last: usize) {
        (self.data_changed)(self.qobject, first, last);
    }
    pub fn begin_reset_model(&mut self) {
        (self.begin_reset_model)(self.qobject);
    }
    pub fn end_reset_model(&mut self) {
        (self.end_reset_model)(self.qobject);
    }
    pub fn begin_insert_rows(&mut self, first: usize, last: usize) {
        (self.begin_insert_rows)(self.qobject, first, last);
    }
    pub fn end_insert_rows(&mut self) {
        (self.end_insert_rows)(self.qobject);
    }
    pub fn begin_move_rows(&mut self, first: usize, last: usize, destination: usize) {
        (self.begin_move_rows)(self.qobject, first, last, destination);
    }
    pub fn end_move_rows(&mut self) {
        (self.end_move_rows)(self.qobject);
    }
    pub fn begin_remove_rows(&mut self, first: usize, last: usize) {
        (self.begin_remove_rows)(self.qobject, first, last);
    }
    pub fn end_remove_rows(&mut self) {
        (self.end_remove_rows)(self.qobject);
    }
}

pub trait HistoryTrait {
    fn new(emit: HistoryEmitter, model: HistoryList) -> Self;
    fn emit(&mut self) -> &mut HistoryEmitter;
    fn row_count(&self) -> usize;
    fn insert_rows(&mut self, _row: usize, _count: usize) -> bool { false }
    fn remove_rows(&mut self, _row: usize, _count: usize) -> bool { false }
    fn can_fetch_more(&self) -> bool {
        false
    }
    fn fetch_more(&mut self) {}
    fn sort(&mut self, u8, SortOrder) {}
    fn author(&self, index: usize) -> &str;
    fn message(&self, index: usize) -> &str;
    fn oid(&self, index: usize) -> &str;
    fn time(&self, index: usize) -> &str;
}

#[no_mangle]
pub extern "C" fn history_new(
    history: *mut HistoryQObject,
    history_new_data_ready: fn(*mut HistoryQObject),
    history_layout_about_to_be_changed: fn(*mut HistoryQObject),
    history_layout_changed: fn(*mut HistoryQObject),
    history_data_changed: fn(*mut HistoryQObject, usize, usize),
    history_begin_reset_model: fn(*mut HistoryQObject),
    history_end_reset_model: fn(*mut HistoryQObject),
    history_begin_insert_rows: fn(*mut HistoryQObject, usize, usize),
    history_end_insert_rows: fn(*mut HistoryQObject),
    history_begin_move_rows: fn(*mut HistoryQObject, usize, usize, usize),
    history_end_move_rows: fn(*mut HistoryQObject),
    history_begin_remove_rows: fn(*mut HistoryQObject, usize, usize),
    history_end_remove_rows: fn(*mut HistoryQObject),
) -> *mut History {
    let history_emit = HistoryEmitter {
        qobject: Arc::new(AtomicPtr::new(history)),
        new_data_ready: history_new_data_ready,
    };
    let model = HistoryList {
        qobject: history,
        layout_about_to_be_changed: history_layout_about_to_be_changed,
        layout_changed: history_layout_changed,
        data_changed: history_data_changed,
        begin_reset_model: history_begin_reset_model,
        end_reset_model: history_end_reset_model,
        begin_insert_rows: history_begin_insert_rows,
        end_insert_rows: history_end_insert_rows,
        begin_move_rows: history_begin_move_rows,
        end_move_rows: history_end_move_rows,
        begin_remove_rows: history_begin_remove_rows,
        end_remove_rows: history_end_remove_rows,
    };
    let d_history = History::new(history_emit, model);
    Box::into_raw(Box::new(d_history))
}

#[no_mangle]
pub unsafe extern "C" fn history_free(ptr: *mut History) {
    Box::from_raw(ptr).emit().clear();
}

#[no_mangle]
pub unsafe extern "C" fn history_row_count(ptr: *const History) -> c_int {
    to_c_int((&*ptr).row_count())
}
#[no_mangle]
pub unsafe extern "C" fn history_insert_rows(ptr: *mut History, row: c_int, count: c_int) -> bool {
    (&mut *ptr).insert_rows(to_usize(row), to_usize(count))
}
#[no_mangle]
pub unsafe extern "C" fn history_remove_rows(ptr: *mut History, row: c_int, count: c_int) -> bool {
    (&mut *ptr).remove_rows(to_usize(row), to_usize(count))
}
#[no_mangle]
pub unsafe extern "C" fn history_can_fetch_more(ptr: *const History) -> bool {
    (&*ptr).can_fetch_more()
}
#[no_mangle]
pub unsafe extern "C" fn history_fetch_more(ptr: *mut History) {
    (&mut *ptr).fetch_more()
}
#[no_mangle]
pub unsafe extern "C" fn history_sort(
    ptr: *mut History,
    column: u8,
    order: SortOrder,
) {
    (&mut *ptr).sort(column, order)
}

#[no_mangle]
pub unsafe extern "C" fn history_data_author(
    ptr: *const History, row: c_int,
    d: *mut QString,
    set: fn(*mut QString, *const c_char, len: c_int),
) {
    let o = &*ptr;
    let data = o.author(to_usize(row));
    let s: *const c_char = data.as_ptr() as (*const c_char);
    set(d, s, to_c_int(data.len()));
}

#[no_mangle]
pub unsafe extern "C" fn history_data_message(
    ptr: *const History, row: c_int,
    d: *mut QString,
    set: fn(*mut QString, *const c_char, len: c_int),
) {
    let o = &*ptr;
    let data = o.message(to_usize(row));
    let s: *const c_char = data.as_ptr() as (*const c_char);
    set(d, s, to_c_int(data.len()));
}

#[no_mangle]
pub unsafe extern "C" fn history_data_oid(
    ptr: *const History, row: c_int,
    d: *mut QString,
    set: fn(*mut QString, *const c_char, len: c_int),
) {
    let o = &*ptr;
    let data = o.oid(to_usize(row));
    let s: *const c_char = data.as_ptr() as (*const c_char);
    set(d, s, to_c_int(data.len()));
}

#[no_mangle]
pub unsafe extern "C" fn history_data_time(
    ptr: *const History, row: c_int,
    d: *mut QString,
    set: fn(*mut QString, *const c_char, len: c_int),
) {
    let o = &*ptr;
    let data = o.time(to_usize(row));
    let s: *const c_char = data.as_ptr() as (*const c_char);
    set(d, s, to_c_int(data.len()));
}

pub struct RepositoriesQObject {}

pub struct RepositoriesEmitter {
    qobject: Arc<AtomicPtr<RepositoriesQObject>>,
    new_data_ready: fn(*mut RepositoriesQObject),
}

unsafe impl Send for RepositoriesEmitter {}

impl RepositoriesEmitter {
    /// Clone the emitter
    ///
    /// The emitter can only be cloned when it is mutable. The emitter calls
    /// into C++ code which may call into Rust again. If emmitting is possible
    /// from immutable structures, that might lead to access to a mutable
    /// reference. That is undefined behaviour and forbidden.
    pub fn clone(&mut self) -> RepositoriesEmitter {
        RepositoriesEmitter {
            qobject: self.qobject.clone(),
            new_data_ready: self.new_data_ready,
        }
    }
    fn clear(&self) {
        let n: *const RepositoriesQObject = null();
        self.qobject.store(n as *mut RepositoriesQObject, Ordering::SeqCst);
    }
    pub fn new_data_ready(&mut self) {
        let ptr = self.qobject.load(Ordering::SeqCst);
        if !ptr.is_null() {
            (self.new_data_ready)(ptr);
        }
    }
}

#[derive(Clone)]
pub struct RepositoriesList {
    qobject: *mut RepositoriesQObject,
    layout_about_to_be_changed: fn(*mut RepositoriesQObject),
    layout_changed: fn(*mut RepositoriesQObject),
    data_changed: fn(*mut RepositoriesQObject, usize, usize),
    begin_reset_model: fn(*mut RepositoriesQObject),
    end_reset_model: fn(*mut RepositoriesQObject),
    begin_insert_rows: fn(*mut RepositoriesQObject, usize, usize),
    end_insert_rows: fn(*mut RepositoriesQObject),
    begin_move_rows: fn(*mut RepositoriesQObject, usize, usize, usize),
    end_move_rows: fn(*mut RepositoriesQObject),
    begin_remove_rows: fn(*mut RepositoriesQObject, usize, usize),
    end_remove_rows: fn(*mut RepositoriesQObject),
}

impl RepositoriesList {
    pub fn layout_about_to_be_changed(&mut self) {
        (self.layout_about_to_be_changed)(self.qobject);
    }
    pub fn layout_changed(&mut self) {
        (self.layout_changed)(self.qobject);
    }
    pub fn data_changed(&mut self, first: usize, last: usize) {
        (self.data_changed)(self.qobject, first, last);
    }
    pub fn begin_reset_model(&mut self) {
        (self.begin_reset_model)(self.qobject);
    }
    pub fn end_reset_model(&mut self) {
        (self.end_reset_model)(self.qobject);
    }
    pub fn begin_insert_rows(&mut self, first: usize, last: usize) {
        (self.begin_insert_rows)(self.qobject, first, last);
    }
    pub fn end_insert_rows(&mut self) {
        (self.end_insert_rows)(self.qobject);
    }
    pub fn begin_move_rows(&mut self, first: usize, last: usize, destination: usize) {
        (self.begin_move_rows)(self.qobject, first, last, destination);
    }
    pub fn end_move_rows(&mut self) {
        (self.end_move_rows)(self.qobject);
    }
    pub fn begin_remove_rows(&mut self, first: usize, last: usize) {
        (self.begin_remove_rows)(self.qobject, first, last);
    }
    pub fn end_remove_rows(&mut self) {
        (self.end_remove_rows)(self.qobject);
    }
}

pub trait RepositoriesTrait {
    fn new(emit: RepositoriesEmitter, model: RepositoriesList) -> Self;
    fn emit(&mut self) -> &mut RepositoriesEmitter;
    fn add(&mut self, index: u64, path: String) -> bool;
    fn remove(&mut self, index: u64) -> bool;
    fn row_count(&self) -> usize;
    fn insert_rows(&mut self, _row: usize, _count: usize) -> bool { false }
    fn remove_rows(&mut self, _row: usize, _count: usize) -> bool { false }
    fn can_fetch_more(&self) -> bool {
        false
    }
    fn fetch_more(&mut self) {}
    fn sort(&mut self, u8, SortOrder) {}
    fn current(&self, index: usize) -> bool;
    fn set_current(&mut self, index: usize, bool) -> bool;
    fn display_name(&self, index: usize) -> &str;
    fn id(&self, index: usize) -> u64;
}

#[no_mangle]
pub extern "C" fn repositories_new(
    repositories: *mut RepositoriesQObject,
    repositories_new_data_ready: fn(*mut RepositoriesQObject),
    repositories_layout_about_to_be_changed: fn(*mut RepositoriesQObject),
    repositories_layout_changed: fn(*mut RepositoriesQObject),
    repositories_data_changed: fn(*mut RepositoriesQObject, usize, usize),
    repositories_begin_reset_model: fn(*mut RepositoriesQObject),
    repositories_end_reset_model: fn(*mut RepositoriesQObject),
    repositories_begin_insert_rows: fn(*mut RepositoriesQObject, usize, usize),
    repositories_end_insert_rows: fn(*mut RepositoriesQObject),
    repositories_begin_move_rows: fn(*mut RepositoriesQObject, usize, usize, usize),
    repositories_end_move_rows: fn(*mut RepositoriesQObject),
    repositories_begin_remove_rows: fn(*mut RepositoriesQObject, usize, usize),
    repositories_end_remove_rows: fn(*mut RepositoriesQObject),
) -> *mut Repositories {
    let repositories_emit = RepositoriesEmitter {
        qobject: Arc::new(AtomicPtr::new(repositories)),
        new_data_ready: repositories_new_data_ready,
    };
    let model = RepositoriesList {
        qobject: repositories,
        layout_about_to_be_changed: repositories_layout_about_to_be_changed,
        layout_changed: repositories_layout_changed,
        data_changed: repositories_data_changed,
        begin_reset_model: repositories_begin_reset_model,
        end_reset_model: repositories_end_reset_model,
        begin_insert_rows: repositories_begin_insert_rows,
        end_insert_rows: repositories_end_insert_rows,
        begin_move_rows: repositories_begin_move_rows,
        end_move_rows: repositories_end_move_rows,
        begin_remove_rows: repositories_begin_remove_rows,
        end_remove_rows: repositories_end_remove_rows,
    };
    let d_repositories = Repositories::new(repositories_emit, model);
    Box::into_raw(Box::new(d_repositories))
}

#[no_mangle]
pub unsafe extern "C" fn repositories_free(ptr: *mut Repositories) {
    Box::from_raw(ptr).emit().clear();
}

#[no_mangle]
pub unsafe extern "C" fn repositories_add(ptr: *mut Repositories, index: u64, path_str: *const c_ushort, path_len: c_int) -> bool {
    let mut path = String::new();
    set_string_from_utf16(&mut path, path_str, path_len);
    let o = &mut *ptr;
    let r = o.add(index, path);
    r
}

#[no_mangle]
pub unsafe extern "C" fn repositories_remove(ptr: *mut Repositories, index: u64) -> bool {
    let o = &mut *ptr;
    let r = o.remove(index);
    r
}

#[no_mangle]
pub unsafe extern "C" fn repositories_row_count(ptr: *const Repositories) -> c_int {
    to_c_int((&*ptr).row_count())
}
#[no_mangle]
pub unsafe extern "C" fn repositories_insert_rows(ptr: *mut Repositories, row: c_int, count: c_int) -> bool {
    (&mut *ptr).insert_rows(to_usize(row), to_usize(count))
}
#[no_mangle]
pub unsafe extern "C" fn repositories_remove_rows(ptr: *mut Repositories, row: c_int, count: c_int) -> bool {
    (&mut *ptr).remove_rows(to_usize(row), to_usize(count))
}
#[no_mangle]
pub unsafe extern "C" fn repositories_can_fetch_more(ptr: *const Repositories) -> bool {
    (&*ptr).can_fetch_more()
}
#[no_mangle]
pub unsafe extern "C" fn repositories_fetch_more(ptr: *mut Repositories) {
    (&mut *ptr).fetch_more()
}
#[no_mangle]
pub unsafe extern "C" fn repositories_sort(
    ptr: *mut Repositories,
    column: u8,
    order: SortOrder,
) {
    (&mut *ptr).sort(column, order)
}

#[no_mangle]
pub unsafe extern "C" fn repositories_data_current(ptr: *const Repositories, row: c_int) -> bool {
    let o = &*ptr;
    o.current(to_usize(row)).into()
}

#[no_mangle]
pub unsafe extern "C" fn repositories_set_data_current(
    ptr: *mut Repositories, row: c_int,
    v: bool,
) -> bool {
    (&mut *ptr).set_current(to_usize(row), v)
}

#[no_mangle]
pub unsafe extern "C" fn repositories_data_display_name(
    ptr: *const Repositories, row: c_int,
    d: *mut QString,
    set: fn(*mut QString, *const c_char, len: c_int),
) {
    let o = &*ptr;
    let data = o.display_name(to_usize(row));
    let s: *const c_char = data.as_ptr() as (*const c_char);
    set(d, s, to_c_int(data.len()));
}

#[no_mangle]
pub unsafe extern "C" fn repositories_data_id(ptr: *const Repositories, row: c_int) -> u64 {
    let o = &*ptr;
    o.id(to_usize(row)).into()
}
